allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  vue-demi: true

managePackageManagerVersions: false

shellEmulator: true

strictTrust: false

trustPolicy: no-downgrade
strict-peer-dependencies: false
auto-install-peers: true

trustPolicyExclude:
  - tinyclip
  - tinyexec

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - msw
  - sharp
  - ttf2woff2
