export const englishRoutes: Record<string, string> = {
  '/english': './src/apps/english/pages/index.astro',
  '/english/admin': './src/apps/english/pages/admin.astro',
  '/english/gallery': './src/apps/english/pages/gallery.astro',
  '/english/learner': './src/apps/english/pages/learner.astro',
  '/english/wrong-words': './src/apps/english/pages/wrong-words.astro',
  '/english/api/textbooks': './src/apps/english/pages/api/textbooks.ts',
  '/english/api/textbooks/cover': './src/apps/english/pages/api/textbooks/cover.ts',
  '/english/api/units': './src/apps/english/pages/api/units.ts',
  '/english/api/words': './src/apps/english/pages/api/words.ts',
  '/english/api/sentences': './src/apps/english/pages/api/sentences.ts',
  '/english/api/batch/words': './src/apps/english/pages/api/batch/words.ts',
  '/english/api/batch/sentences': './src/apps/english/pages/api/batch/sentences.ts',
  '/english/api/batch/word-sentences': './src/apps/english/pages/api/batch/word-sentences.ts',
  '/english/api/words-search': './src/apps/english/pages/api/words-search.ts',
}
